spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/db_example'
    username:  ${DB_USER}
    password:  ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org.springframework: ERROR
      org.hibernate: DEBUG

app:
  host: 'http://localhost:8080'
